### ISSUE TITLE
Pizzacı mesleği hk.

### ISSUE THREAD

**Issue by ryzzthe** [inceptionnet/v5-issues-staff#120]
![image](https://github.com/inceptionnet/v5-issues-staff/assets/173103789/1ff127c4-8e5a-4dad-9263-948cfa02294e)

**Comment by ryzzthe** [comment]
Yumruk atılıyor elimizde pizza kutusu varken, ne kadar önemlidir bileeeeemeeeeeeeeeem

**Comment by mahlukat5** [comment]
fix
