### ISSUE TITLE
taşımacılık mesleği

### ISSUE THREAD

**Issue by mores2** [inceptionnet/v5-issues-staff#144]
taşımacılık mesleğinde kutuyu araca götürürken elimize silah alıp ateş edebiliyoruz hangi silah olduğu fark etmiyor.

**Comment by ryzzthe** [comment]
Kargoculuk* mesleği olacaktı sanırım..

**Comment by ryzzthe** [comment]
![image](https://github.com/inceptionnet/v5-issues-staff/assets/173103789/5b9909b3-6a3a-419a-a5b6-e24e7f8c2c19)
@fresholia

**Comment by mahlukat5** [comment]
fix
