### ISSUE TITLE
Casino

### ISSUE THREAD

**Issue by raverqwwq** [inceptionnet/v5-issues-staff#145]
![mta-screen_2024-07-02_01-26-51](https://github.com/inceptionnet/v5-issues-staff/assets/174391882/92bad9d5-ff85-497d-8a3a-b03c37925980)
Casinoda çözünürlüğü düşük olan oyuncular bu sıkıntıyı yaşıyor oyundan çıkmadığı sürece bu ekran gitmiyor.

**Comment by QueryOfficial** [comment]
Kapat butonu tamamen kapatmaya, yanına da geriye dön butonu koyalım. Geriye dönmeye yarasın.

Ya da direk küçük çözünürlükteki pcler için genel görünme sorununu düzeltelim.

![WhatsApp Görsel 2024-06-29 saat 16 53 43_5ef8bcc6](https://github.com/inceptionnet/v5-issues-staff/assets/76632145/064e726c-619f-4e31-9233-0a822830cd1b)
