### ISSUE TITLE
Karakter oluşturma

### ISSUE THREAD

**Issue by raverqwwq** [inceptionnet/v5-issues-staff#146]
![mta-screen_2024-07-02_01-55-18](https://github.com/inceptionnet/v5-issues-staff/assets/174391882/987925a2-4f81-45b1-8546-738dbfdf2652)

Yeni karakter oluşturmada erkek veya kızı seçsek bile hep erkek seçili kalıyor.

**Comment by ryzzthe** [comment]
Sorun test edildi, bir sorunla karşılaşılmadı. Kadın karakter seçtim ve oluşturabildim.
