### ISSUE TITLE
Taşımacılık Mesleği

### ISSUE THREAD

**Issue by raverqwwq** [inceptionnet/v5-issues-staff#148]
![mta-screen_2024-07-02_00-41-42](https://github.com/inceptionnet/v5-issues-staff/assets/174391882/32e82b45-59e0-4f2c-ac01-509edd699a31)
Araçtan in bin yapınca bu mavi yörüngeler bulunmuyor.

**Comment by mahlukat5** [comment]
Gözüküyor normalde fakat tam o sıra marker olan lokasyona denk gelmişin sanırım
büyük ihtimal az ilerledikden sonra in bin yapsan düzelir veye kendisi düzelir
