### ISSUE TITLE
Taksici Mesleği Sorunları

### ISSUE THREAD

**Issue by QueryOfficial** [inceptionnet/v5-issues-staff#160]
- [ ] Taksici mesleğine giriş yaptım, nametag'ım sarı olmadı.
![image](https://github.com/inceptionnet/v5-issues-staff/assets/76632145/cceae342-74a1-470e-b85b-8162f1161314)

- [ ] Ayrıca /taksici yazdığımda aktif taksi yok diyor.
![image](https://github.com/inceptionnet/v5-issues-staff/assets/76632145/e76a858c-c51a-4969-921c-90ea2c77a76d)

- [ ] Taksici mesleğinde olmayan herkes Taksilerin şoför koltuğuna binebiliyor.
![image](https://github.com/inceptionnet/v5-issues-staff/assets/76632145/a87f61ad-ea25-43ad-b7e7-9b4ec0195cca)

**Comment by mahlukat5** [comment]
fix

**Comment by ryzzthe** [comment]
Taksici mesleğinde değilim, yetkim de yok. Araca hala binebiliyorum, ayrıyeten çalıştırabiliyorum.

![image](https://github.com/inceptionnet/v5-issues-staff/assets/173103789/cae27ebf-1561-4378-be3d-ec4628cfcf1d)
