### ISSUE TITLE
Kargoculuk mesleği kutu alınmıyor

### ISSUE THREAD

**Issue by westere-no-cap** [inceptionnet/v5-issues-staff#163]
![image](https://github.com/inceptionnet/v5-issues-staff/assets/173107453/e6a10578-bec5-4a7a-b9a0-0ab98e3d82c2)
debugscript temiz ama kutu alınmıyor bazen keyfine göre.

**Comment by mahlukat5** [comment]
kutunun ön tarafına tıkla ve iyice yaklaşırsan alınacaktır
