### ISSUE TITLE
"/market arayüz hatası" hk.

### ISSUE THREAD

**Issue by ryzzthe** [inceptionnet/v5-issues-staff#166]
Marketten herhangi bir şey satın aldıktan sonra, marketi kapatıp açarsak neye basarsak basalım farklı bir ürün gösteriyor. Atıyorum telefon numarası satın alıp market arayüzünü kapattım, sonrasında açıp ooc jail açtırmaya veye herhangi farklı bir ürüne bastığımda telefon numarası alma ekranı 30 tl ücret olarak gözüküyor almaya çalıştığımızda 30 tlye alınmıyor fakat arayüz hatalı. Ayrıyeten alt tab attığımızda bu durum düzeliyor.

![image](https://github.com/inceptionnet/v5-issues-staff/assets/173103789/43ffddad-331e-499b-801f-c4d954641366)

![image](https://github.com/inceptionnet/v5-issues-staff/assets/173103789/fcafc90f-66df-4bb8-8873-e1c544af5f2d)

**Comment by ozulusrift** [comment]
onClientRestore eventi ile yazılar düzeliyor. bu fonksiyonu modal açıldığında çalıştırırsak düzelir
