### ISSUE TITLE
"/market Range Rover siren" hk.

### ISSUE THREAD

**Issue by ryzzthe** [inceptionnet/v5-issues-staff#167]
Marketten donate olarak alınan range rover siren açabiliyor, araç sadece legal faction üzerine kayıtlıysa siren açabilsin olarak düzeltilmesi gerekiyor. (GTA : 490)

![image](https://github.com/inceptionnet/v5-issues-staff/assets/76632145/39e08f77-a736-469d-8e15-3a998374d8cc)

**Comment by ryzzthe** [comment]
![image](https://github.com/inceptionnet/v5-issues-staff/assets/173103789/257cc013-750e-4ad8-b3be-8c1e62eb12ec)

**Comment by ozulusrift** [comment]
fix

**Comment by ryzzthe** [comment]
fixlenmemiş
