### ISSUE TITLE
in_market - HATALAR

### ISSUE THREAD

**Issue by QueryOfficial** [inceptionnet/v5-issues-staff#170]
- [x] Buraya tıkladığımızda geçmiş bakiyeye vs. yönlendiriyor.
![image](https://github.com/inceptionnet/v5-issues-staff/assets/76632145/eed1c167-e77c-43cd-9f63-4e50cadd34aa)

- [x] Tag almaya çalışınca silah alıyormuş gibi tepki veriyor.
![image](https://github.com/inceptionnet/v5-issues-staff/assets/76632145/c980a54b-172d-4af7-be75-bff2a3f0d4b7)

- [x] Polis yetkisi satın almaya çalışırken, (rankName a nil value) hatası veriyor. server.lua:1651
![image](https://github.com/inceptionnet/v5-issues-staff/assets/76632145/088ffbd5-e84b-4bcd-992f-9b825489d5ed)

- [x] VIP satın alırken, indirimli hali 90 günün 336 TL yazıyorken, 335 TL bakiyem varken aldım. Bakiye de arttı.
![image](https://github.com/inceptionnet/v5-issues-staff/assets/76632145/ddae349f-e621-417f-86ec-7f6e278d57e1)

- [x] %20 indirim vs. tanımladığımızda bu tarz GUI'lerde görünen rakamlarda otomatik değişip güncellensin.
![image](https://github.com/inceptionnet/v5-issues-staff/assets/76632145/874edac4-9495-4823-b8bc-372d20da32ee)

- [x] %20 indirim vs. tanımladığımızda bu tarz GUI'lerde görünen rakamlarda otomatik değişip güncellensin.
![image](https://github.com/inceptionnet/v5-issues-staff/assets/76632145/2687e115-e7b6-440f-933d-c81ae3ac0c0d)

- [x] Animasyonlar'a girdiğim zaman kendi skinim ney ise onu canlandırsın, köpek görünüyor.
![image](https://github.com/inceptionnet/v5-issues-staff/assets/76632145/19bc4d54-4371-4e8a-94e6-d0defc4a63f9)

- [x] OOC Jail ve Silah Kısıtlama 'daki indirimi kaldıralım.
![image](https://github.com/inceptionnet/v5-issues-staff/assets/76632145/281db3a2-b45b-48f5-8c25-e0dc8d6bf7f7)
![image](https://github.com/inceptionnet/v5-issues-staff/assets/76632145/4e478867-2d4c-4cfa-8d55-9d3949901516)

**Comment by ryzzthe** [comment]
4:3 çözünürlükte bu şekilde gözüküyor.

![image](https://github.com/inceptionnet/v5-issues-staff/assets/173103789/cf0c7614-3207-4358-b6c3-b9478fe21144)

**Comment by ryzzthe** [comment]
History sildirme 4 TL yerine GUI üzerinde 5 TL görünüyor. Ancak 4 tl kesiyor.

![image](https://github.com/inceptionnet/v5-issues-staff/assets/173103789/9cb0a521-6f8d-4e6e-b77a-5807f2b92b62)

**Comment by ryzzthe** [comment]
1000 dakika jail attım kendime, 128 tl olarak gözüküyor /markette. GUI üzerinde 160 olarak gözüküyor ve 160 tl kesiyor.

![image](https://github.com/inceptionnet/v5-issues-staff/assets/173103789/95685667-c9db-43c4-bad7-ea2a9c4d95bb)

**Comment by ryzzthe** [comment]
Özel telefon numarası 24 TL gözüküyor, 30 TL kesiyor.

![image](https://github.com/inceptionnet/v5-issues-staff/assets/173103789/d29222c4-fb22-41c5-b8d7-5624b7e113dd)

**Comment by ryzzthe** [comment]
32 gözüküyor indirimli, 40 GUI üzerinde. 32 TL kesiyor.

![image](https://github.com/inceptionnet/v5-issues-staff/assets/173103789/a3509b9c-c64f-4714-8ef0-631580ccc24e)

**Comment by ryzzthe** [comment]
VIP 3 88 TL kesmesi gerekirken 1 aylıkta, 72 TL kesiyor.

![image](https://github.com/inceptionnet/v5-issues-staff/assets/173103789/7f4554fb-bee3-436d-84d7-a2391d3df6bf)

**Comment by ryzzthe** [comment]
VIP4 112 TL kesmesi gerekirken 1 aylıkta, 96 TL kesiyor.

![image](https://github.com/inceptionnet/v5-issues-staff/assets/173103789/1ff37265-6d16-49ee-9dd0-7567b433f169)

**Comment by ryzzthe** [comment]
56 TL olması gerekirken böyle gözüküyor GUI üzerinde, 56 TL kesiyor.

![image](https://github.com/inceptionnet/v5-issues-staff/assets/173103789/e4f74d61-8376-4f62-ae39-64b63abd0f8b)

**Comment by ryzzthe** [comment]
24 yerinde GUI de bu şekilde gözüküyor. 24 TL kesiyor sorun yok.

![image](https://github.com/inceptionnet/v5-issues-staff/assets/173103789/cbea4f56-d09f-4537-a3fe-ebc7ca1d92a6)

**Comment by ryzzthe** [comment]
24 yerine 30 tl gözüküyor, 24 tl kesiyor sorun yok.

![image](https://github.com/inceptionnet/v5-issues-staff/assets/173103789/62eb5dd0-2936-474d-8222-bee0530def8e)

**Comment by ryzzthe** [comment]
32 yerine 40 görünüyor, 32 tl kesiyor sorun yok.

![image](https://github.com/inceptionnet/v5-issues-staff/assets/173103789/21c444c8-0b94-4b80-9814-b85255f0c112)

**Comment by ryzzthe** [comment]
48 olması gerekirken 60, ayrıca satın alınmıyor alamadım. Ne kadar bakiye kestiğini bilmiyorum.

![image](https://github.com/inceptionnet/v5-issues-staff/assets/173103789/dde174ad-98bb-498f-b0c8-9d1db26b81e6)

**Comment by ryzzthe** [comment]
28 olması gerekirken 35, 28 tl kesiyor sorun yok.

![image](https://github.com/inceptionnet/v5-issues-staff/assets/173103789/5c1c7c22-863b-4ed3-966e-49a43cfac2f7)

**Comment by ryzzthe** [comment]
Etiketlerin hiçbiri gösterdiği parayı kesmiyor, indirimli değil. Atıyorum 32 kesecekken 40 kesiyor.
![image](https://github.com/inceptionnet/v5-issues-staff/assets/173103789/f60d1678-0032-4aa2-b0a3-9994b4c1650a)

**Comment by ryzzthe** [comment]
LSPD rütbeleri satın alınmıyor. Bakiye de kesmiyor, birliğe de almıyor.

![image](https://github.com/inceptionnet/v5-issues-staff/assets/173103789/98509f2e-21d6-4455-8119-47e00816e8df)

**Comment by ryzzthe** [comment]
100 saat olmama rağmen yetkiler satın alınmıyor, bu uyarıyı veriyor.

![image](https://github.com/inceptionnet/v5-issues-staff/assets/173103789/2b954f9b-8a05-41f7-8de6-ba51f51e81d7)

**Comment by ryzzthe** [comment]
Silah fiyatları düzenlenmeli, 360 gösteriyor M4 ancak 450 TL kesiyor.

![image](https://github.com/inceptionnet/v5-issues-staff/assets/173103789/7ce09752-c2fb-41d5-9ab7-e1c0d485da86)
