### ISSUE TITLE
"Kargocu mesleği"sorun hk.

### ISSUE THREAD

**Issue by ryzzthe** [inceptionnet/v5-issues-staff#171]
Kutular ele alınca gözükmüyor, silah elimize alınabiliyor aim açıp tekrar kapatınca kutu taşıma animasyonu da bozuluyor. Her iki screenshot üzerinde de elimde kutu var.

![image](https://github.com/inceptionnet/v5-issues-staff/assets/173103789/93e96eac-796f-4aca-b9c9-45519662b37b)

![image](https://github.com/inceptionnet/v5-issues-staff/assets/173103789/dfa6e99c-d543-4065-9766-3a38eb4836db)

**Comment by mahlukat5** [comment]
bende kutular gözüküyor sende sorun var sanırım
