### ISSUE TITLE
/hud vs. yazdığımız zaman heryerin alpha'sı kısılıyor voice kısılmıyor

### ISSUE THREAD

**Issue by QueryOfficial** [inceptionnet/v5-issues-staff#175]
/hud vs. yazdığımız zaman heryerin alpha'sı kısılıyor voice kısılmıyor
![image](https://github.com/inceptionnet/v5-issues-staff/assets/76632145/f83a40d6-fd2c-425b-8ce7-006c391eb677)

**Comment by fresholia** [comment]
Voice'in postGUI render olması gerekiyor bundan dolayı çok da büyük bir problem değil
