### ISSUE TITLE
Adminler için /places çalışmıyor

### ISSUE THREAD

**Issue by Neironn** [inceptionnet/v5-issues-staff#20]
/places yazdığımızda konum söylemesi gerekirken söylemiyor, ek olarak kendimizi bir yere (örn. /gonder [ID] binco) yaptığımızda "Alan bulunamadı, alanlar /places komutu ile bakabilirsiniz." hatasını veriyor.
![image](https://github.com/inceptionnet/v5-issues-staff/assets/86184318/07d5ec69-0ea4-41ac-a25d-52b4707290d7)

**Comment by ryzzthe** [comment]
Eklenebiliyor, sistemde sorun yok.

**Comment by fresholia** [comment]
Geliştirme sunucusu olduğundan ekli place yok, bu sistemde sorun yok
