### ISSUE TITLE
Taksici mesleğine başlanıyor, ancak bırakılmıyor. Ayrıca taksi mesleği ile ilgili bir öneri.

### ISSUE THREAD

**Issue by ryzzthe** [inceptionnet/v5-issues-staff#40]
Taksici mesleğine başlamada bir sorun yok, taksimetre sorunsuz çalışıyor. Taksimetre sıfırlama da aynı şekilde sorunsuz. Taksi mesleğine başlanılan yere tekrar girildiğinde meslek bırakılmıyor, herhangi bir panel açılmıyor screenshot üzerindeki gibi. Araçtan uzaklaşınca meslekten atıyor bir süre sonra ancak, manuel olarak işten ayırlamıyoruz. Taksimetre sistemi ile alakalı paranın müşteriden otomatik alınması gibi bir sistem yapılabilir, oyuncular manuel vermek zorunda ve bu suistimal edilebilir.
![image](https://github.com/inceptionnet/v5-issues-staff/assets/173103789/a1393767-15e9-439a-8302-3336eca59473)

**Comment by ryzzthe** [comment]
Ekleme = Taksiye bir süre bindiğimizde meslekten atmış olarak gözüküyor fakat yine meslekten atmıyor, başka herhangi bir mesleğe girilmiyor bu yüzden.

**Comment by mahlukat5** [comment]
fix
