### ISSUE TITLE
giris ekrenı sorunu

### ISSUE THREAD

**Issue by MytsicRapier468** [inceptionnet/v5-issues-staff#56]
https://streamable.com/huuewe

**Comment by fresholia** [comment]
Sorunu tam olarak anlayamadım, anlatır mısın? @MytsicRapier468

**Comment by MytsicRapier468** [comment]
Kanka şimdi giriş ekranında kaydolma yerinde değilde giriş ekranında
şifreni ve hesabını  yazmaya çalıştığında birden yazılar gidiyor sorun
burda

19 Haz 2024 Çar 14:43 tarihinde enes akilliok ***@***.***>
şunu yazdı:
