### ISSUE TITLE
Stacklenme sorunu

### ISSUE THREAD

**Issue by fuanex** [inceptionnet/v5-issues-staff#64]
Envanterde aynı tip veya aynı eşyadan alınca stacklenmiyor.
![eşyalar stacklenmiyor](https://github.com/inceptionnet/v5-issues-staff/assets/173103736/622d6dfa-2a7a-434c-a555-6a55503102d0)

**Comment by ryzzthe** [comment]
Stacklenme sistemi kaldırılacak, bug oluşumuna sebep olabiliyor. İtemler ayrı ayrı gözükecek.
