### ISSUE TITLE
meslekte mesafe yanlış yazıyor

### ISSUE THREAD

**Issue by mores2** [inceptionnet/v5-issues-staff#73]
taşımacılık mesleğine başladığımız zaman üstte bulunan mesafe yanlış gösteriyor full 4743 mt'de kalıyor.

**Comment by mahlukat5** [comment]
yanlış göstermiyor
ordaki mt sen ilerledikçe düşmez. onun altındaki bar düşer. o mt toplam gitmen gereken mesafeyi gösteriyor
