### ISSUE TITLE
Toplu Bug

### ISSUE THREAD

**Issue by Foxyy3** [inceptionnet/v5-issues-staff#75]
### Uyarı: Bir meslekten ayrılmadan bir yere gitmeyin mesela balıkçılıkta meslekten ayrılmadığınız sürece sol tarafta olta ve yem yazıları çıkar başka mesleklere giremezsiniz. Bilgilendirmek istedim.

1- Kargoculuk mesleği çok uzun sürüyor oyuncuları bayıyor ve parası az eğer parası yükselirse daha verimli olur.
2- Taksi mesleğinde araca binince rota çıkıyor ve taksimetre yazısını kapatıyor araçtan inince belli bir süre sonra meslekten atıldınız diyor fakat meslekten atmıyor buga giriyor mesleğe tekrardan başlayamıyoruz.
3-Rotalı mesleklerde bazen rota yanlış gösteriyor mesela köprü altı gibi yerlere rota atıyor ama köprünün üzerindeymiş gibi rota koyuyor.
4- Taba bastığımızdaki oyuncu paneli buglu aşşağı kaydırınca yukarı tarafı buga düşüyor boşluk oluyor.
5- F10 a basınca arkadaki karakterin ismi f10 panelinin yazılarını kapatıyor. f10 panelinde ooc markete tıklayınca yetersiz bakiye uyarısı veriyor.
Şimdilik bu kadar buldum şahsen yardımcı olabilmişimdir umarım, elinize emeğinize sağlık.

**Comment by mahlukat5** [comment]
2 - 
![image](https://github.com/inceptionnet/v5-issues-staff/assets/29680029/0e6b6175-c201-473f-b2c2-d2afc38075ad)
o kadar kapatmıyor aslında. sende nasıl gözüküyor ss atabilir misin? (diğer bug fix)
3 - onlar gtanın gps hataları maalesef ya. 3d blip çıkıyor haritada onu takip etmek en sağlıklısı.
