### ISSUE TITLE
Emniyet Kemeri sistemi.

### ISSUE THREAD

**Issue by gercekburak** [inceptionnet/v5-issues-staff#76]
V4'te, araçta emniyet kemeri takılıyken araçtan inmek istediğimiz zaman "Emniyet Kemeri takılıyken araçtan inemezsiniz." hatası veriyordu. V5'te kemer takıp araçtan inmek istediğimiz zaman herhangi bir uyarı ile karşılaşmıyoruz, direkt olarak iniyor. 

![image](https://github.com/inceptionnet/v5-issues-staff/assets/156973409/5a9ea763-e195-4b3e-9cbd-2d3863223e74)
![image](https://github.com/inceptionnet/v5-issues-staff/assets/156973409/28372a8c-cea9-4e8f-88df-63e948f426a6)

**Comment by fresholia** [comment]
Bu sistem kaldırıldı
