### ISSUE TITLE
Kelepçeleme sistemi hatalı.

### ISSUE THREAD

**Issue by ryzzthe** [inceptionnet/v5-issues-staff#77]
5 seviyeyim, kelepçelemeye çalıştığım zaman birisini en az 2 seviye olmanız gerekiyor diyor.

![image](https://github.com/inceptionnet/v5-issues-staff/assets/173103789/ca0ae1b5-b7a5-42c1-bb19-eaa750ccca27)

**Comment by mahlukat5** [comment]
fix
