### ISSUE TITLE
Meslek araçlarını toplu yenileme.

### ISSUE THREAD

**Issue by gercekburak** [inceptionnet/v5-issues-staff#78]
V4'te /respawnciv komudu ile "Sadece Meslek" araçlarını yenileyebiliyorduk.  V5'te bu komut direkt olarak yok.

![image](https://github.com/inceptionnet/v5-issues-staff/assets/156973409/5a64983e-8f04-438a-aac4-813079f685a1)

**Comment by mahlukat5** [comment]
çünkü artık meslek araçları yok. sağda solda bir kaç tane kaldıysada kalkacak.
yeni görev düzeninde göreve girince verilior oyuncuya araç
