### ISSUE TITLE
Chatteki yazıların büyüklüğü hk.

### ISSUE THREAD

**Issue by Davydtr** [inceptionnet/v5-issues-staff#92]
Chat üzerindeki yazılar çok küçük gözüküyor, zar zor okunuyor. çözünürlükle alakalı olabilir, çözünürlüğüm 1366x768 - 4:3

![image](https://github.com/inceptionnet/v5-issues-staff/assets/173105384/248d0d51-0607-49e4-8fd8-b8f908e55369)

**Comment by sinan123831** [comment]
Bendede aynı durum var, düzeltilebilir.
